# Practice data structures

We will create a data structure to hold our Germplasm data (I have updated it to be a little bit more complex... now a germplasm may hold TWO alleles - i.e. one germplasm has connections to more than one gene)

Represent these data in Python - create a **single variable** that contains all of this data (using lists and dictionaries).

Create loops over that data structure that can print the three tables to the screen.







<center>stock table</center>

germplasm_id |  amount  |  date  |  location  
 --- | --- | --- | --- 
 2 |  5  | 10/5/2013 |  Room 2234  
 1 | 9.8  | 12/1/2015 |  Room 998  


-----------------------------


<center>germplasm table</center>

id |  taxonid  |  alleles | genes 
 --- |--- | --- | ---
 1 |  4150  | def-1 | DEF
 2 | 3701  | ap3,  ag | AP3, AG
  
--------------------------------

<center>gene table</center>

  gene  |  gene_name  |  embl
 --- | ---  | --- 
  DEF  | Deficiens  | https://www.ebi.ac.uk/ena/data/view/AB516402
  AP3  | Apetala3   |   https://www.ebi.ac.uk/ena/data/view/AF056541
  AG  | Agamous   |   https://www.ebi.ac.uk/ena/data/view/AL161549
  

In [15]:
stocks = []
stock = {"germplasm_id":2, "amount":5, "date": "10/05/2013", "location": "Room 2234"}
stocks.append(stock)
stock = {"germplasm_id":1, "amount":9.8, "date": "12/01/2015", "location": "Room 998"}
stocks.append(stock)
#print(stocks)

germplasms = []
germplasm = {"id": 1, "taxonid": 4150, "alleles": "def-1", "genes": "DEF"}
germplasms.append(germplasm)
alleles2 = ["ap3","ag"]
genes2 = ["AP3", "AG"]
germplasm = {"id": 2, "taxonid": 3701, "alleles": alleles2, "genes": genes2}
germplasms.append(germplasm)
#print(germplasms)

genes = []
gene = {"gene": "DEF", "gene_name": "Deficiens", "embl":"https://www.ebi.ac.uk/ena/data/view/AB516402"}
genes.append(gene)
gene = {"gene": "AP3", "gene_name": "Aapetala3", "embl":"https://www.ebi.ac.uk/ena/data/view/AF056541"}
genes.append(gene)
gene = {"gene": "AG", "gene_name": "Agamous", "embl":"https://www.ebi.ac.uk/ena/data/view/AL161549"}
genes.append(gene)
#print(genes)

all = [stocks, germplasms, genes]
print(all)

[[{'germplasm_id': 2, 'amount': 5, 'date': '10/05/2013', 'location': 'Room 2234'}, {'germplasm_id': 1, 'amount': 9.8, 'date': '12/01/2015', 'location': 'Room 998'}], [{'id': 1, 'taxonid': 4150, 'alleles': 'def-1', 'genes': 'DEF'}, {'id': 2, 'taxonid': 3701, 'alleles': ['ap3', 'ag'], 'genes': ['AP3', 'AG']}], [{'gene': 'DEF', 'gene_name': 'Deficiens', 'embl': 'https://www.ebi.ac.uk/ena/data/view/AB516402'}, {'gene': 'AP3', 'gene_name': 'Aapetala3', 'embl': 'https://www.ebi.ac.uk/ena/data/view/AF056541'}, {'gene': 'AG', 'gene_name': 'Agamous', 'embl': 'https://www.ebi.ac.uk/ena/data/view/AL161549'}]]


In [29]:
#puedes hacer tamibén que las posiciones tengan sentido de forma que
genes = {}
gene1 = {"gene": "DEF", "gene_name": "Deficiens", "embl":"https://www.ebi.ac.uk/ena/data/view/AB516402"}
genes["DEF"]=gene1
gene2 = {"gene": "AP3", "gene_name": "Aapetala3", "embl":"https://www.ebi.ac.uk/ena/data/view/AF056541"}
genes["AP3"]=gene2
gene3 = {"gene": "AG", "gene_name": "Agamous", "embl":"https://www.ebi.ac.uk/ena/data/view/AL161549"}
genes["AG"]=gene3
print(genes.keys())

germplasms = {}
germplasm = {"id": 1, "taxonid": 4150, "alleles": "def-1", "genes": [genes["DEF"]]}
germplasms[1]=germplasm
germplasm = {"id": 2, "taxonid": 3701, "alleles": alleles2, "genes": [genes["AP3"], genes["AG"]]}
germplasms[2]=germplasm

stocks = {}
stock = {"germplasm_id": germplasms[2], "amount":5, "date": "10/05/2013", "location": "Room 2234"}
stocks[1]=stock
stock = {"germplasm_id": germplasms[1], "amount":9.8, "date": "12/01/2015", "location": "Room 998"}
stocks[2]=stock

print(stocks)


dict_keys(['DEF', 'AP3', 'AG'])
{1: {'germplasm_id': {'id': 2, 'taxonid': 3701, 'alleles': ['ap3', 'ag'], 'genes': [{'gene': 'AP3', 'gene_name': 'Aapetala3', 'embl': 'https://www.ebi.ac.uk/ena/data/view/AF056541'}, {'gene': 'AG', 'gene_name': 'Agamous', 'embl': 'https://www.ebi.ac.uk/ena/data/view/AL161549'}]}, 'amount': 5, 'date': '10/05/2013', 'location': 'Room 2234'}, 2: {'germplasm_id': {'id': 1, 'taxonid': 4150, 'alleles': 'def-1', 'genes': [{'gene': 'DEF', 'gene_name': 'Deficiens', 'embl': 'https://www.ebi.ac.uk/ena/data/view/AB516402'}]}, 'amount': 9.8, 'date': '12/01/2015', 'location': 'Room 998'}}


SIMPLE ANSWER (hidden below)

More complex...

Optimal

simple

<span style="visibility:hidden;">
# put your code here... take it one step at a time!
# do just one table
genes = []
gene = {"gene": "DEF", "gene_name": "Deficiens", "embl": "https://www.ebi.ac.uk/ena/data/view/AB516402"}
genes.append(gene)
gene = {"gene": "AP3", "gene_name": "Apetala3", "embl": "https://www.ebi.ac.uk/ena/data/view/AF056541"}
genes.append(gene)
gene = {"gene": "AG", "gene_name": "Agamous", "embl": "https://www.ebi.ac.uk/ena/data/view/AL161549"}
genes.append(gene)

print(genes)

germplasms = []
germplasm = {"id": 1, "taxonid": 4150, "alleles": ["def-1"], "genes": ["DEF"]}
germplasms.append(germplasm)
germplasm = {"id": 2, "taxonid": 3710, "alleles": ["ap3", "ag"], "genes": ["AP3", "AG"]}
germplasms.append(germplasm)

print(germplasms)


stocks = []
stock = {"germplasm": 2, "amount": 5, "date": "10/5/2013", "location": "Room 2234"}
stocks.append(stock)
stock = {"germplasm": 1, "amount": 9.8, "date": "12/1/2015", "location": "Room 998"}
stocks.append(stock)

print(stocks)

</span>

more complex

<span style="visibility:hidden;">
    
    # put your code here... take it one step at a time!
# do just one table
genes = {}
gene = {"gene": "DEF", "gene_name": "Deficiens", "embl": "https://www.ebi.ac.uk/ena/data/view/AB516402"}
genes["DEF"] = gene
gene = {"gene": "AP3", "gene_name": "Apetala3", "embl": "https://www.ebi.ac.uk/ena/data/view/AF056541"}
genes["AP3"] = gene
gene = {"gene": "AG", "gene_name": "Agamous", "embl": "https://www.ebi.ac.uk/ena/data/view/AL161549"}
genes["AG"] = gene

print(genes)


germplasms = {}
germplasm = {"id": 1, "taxonid": 4150, "alleles": ["def-1"], "genes": ["DEF"]}
germplasms[1] = germplasm
germplasm = {"id": 2, "taxonid": 3710, "alleles": ["ap3", "ag"], "genes": ["AP3", "AG"]}
germplasms[2] = germplasm

print(germplasms)


stocks = {}
stock = {"germplasm": 2, "amount": 5, "date": "10/5/2013", "location": "Room 2234"}
stocks[1] = stock
stock = {"germplasm": 1, "amount": 9.8, "date": "12/1/2015", "location": "Room 998"}
stocks[2] = stock

print(stocks)

print(genes["DEF"]["embl"])

<span>

In [27]:



# put your code here... take it one step at a time!
# do just one table

genes = {}
gene = {"gene": "DEF", "gene_name": "Deficiens", "embl": "https://www.ebi.ac.uk/ena/data/view/AB516402"}
genes["DEF"] = gene
gene = {"gene": "AP3", "gene_name": "Apetala3", "embl": "https://www.ebi.ac.uk/ena/data/view/AF056541"}
genes["AP3"] = gene
gene = {"gene": "AG", "gene_name": "Agamous", "embl": "https://www.ebi.ac.uk/ena/data/view/AL161549"}
genes["AG"] = gene

#print(genes)

germplasms = {}
germplasm = {"id": 1, "taxonid": 4150, "alleles": ["def-1"], "genes": [genes["DEF"]]}
germplasms[1] = germplasm
germplasm = {"id": 2, "taxonid": 3710, "alleles": ["ap3", "ag"], "genes": [genes["AP3"], genes["AG"]]}
germplasms[2] = germplasm

print(germplasms.keys())

stocks = {}
stock = {"germplasm": germplasms[2], "amount": 5, "date": "10/5/2013", "location": "Room 2234"}
stocks[1] = stock
stock = {"germplasm": germplasms[1], "amount": 9.8, "date": "12/1/2015", "location": "Room 998"}
stocks[2] = stock

print(stocks.keys())

for s in stocks.keys():
    print("location: ", stocks[s]["location"])
    print("germplasm taxon: ",  stocks[s]["germplasm"]["taxonid"])
    print("germplasm taxon: ",  stocks[s]["germplasm"]["genes"][0]["embl"])
    
print("\n\nreaching into the objects...\n\n")
for s in stocks.keys():
    print("location: ", stocks[s]["location"])
    print("germplasm taxon: ",  stocks[s]["germplasm"]["taxonid"])
    for gene in stocks[s]["germplasm"]["genes"]:
        print("Gene Name: ", gene["gene_name"], " with embl url: ", gene["embl"])


dict_keys([1, 2])
dict_keys([1, 2])
location:  Room 2234
germplasm taxon:  3710
germplasm taxon:  https://www.ebi.ac.uk/ena/data/view/AF056541
location:  Room 998
germplasm taxon:  4150
germplasm taxon:  https://www.ebi.ac.uk/ena/data/view/AB516402


reaching into the objects...


location:  Room 2234
germplasm taxon:  3710
Gene Name:  Apetala3  with embl url:  https://www.ebi.ac.uk/ena/data/view/AF056541
Gene Name:  Agamous  with embl url:  https://www.ebi.ac.uk/ena/data/view/AL161549
location:  Room 998
germplasm taxon:  4150
Gene Name:  Deficiens  with embl url:  https://www.ebi.ac.uk/ena/data/view/AB516402


<span style="visibility:hidden;">
DEF = {'id': 'DEF', 'name': 'Deficiens', 'embl': 'http://AB123434'}
AP3 = {'id': 'AP3', 'name': 'Apetala3', 'embl': 'http://AB123434'}
AG = {'id': 'AG', 'name': 'Agamous', 'embl': 'http://AB123434'}
gp1 = {'id': 1, 'taxon': 4150, 'alleles': ['def1'], 'genes': [DEF]}
gp2 = {'id': 2, 'taxon': 4150, 'alleles': ['ap3', 'ag'], 'genes': [AP3, AG]}
stock1 = {'germplasm': gp2, 'amount': 5, 'date': '10/5/2013', 'location': 'Room 2234' }
stock2 = {'germplasm': gp1, 'amount': 9.8, 'date': '12/1/2015', 'location': 'Room 998' }
database = [stock1, stock2]
for stock in database:
    print(stock['germplasm']['id'], ", ", stock['amount'],",",stock['date'],",",stock['location'])
</span>